### ISSUE TITLE
Trojan redirect

### ISSUE THREAD

**Issue by gonebeta** [srikat/one-pager-genesis#11]
Hey,

It seems you have a trojan on the demo site.
Here's what my anti-virus says:
..............
Threat found
This web page contains potentially dangerous content.

Threat: JS/Redirector.NDR trojan

Access to it has been blocked. 
......
Look into that.

**Comment by srikat** [comment]
Thanks for bringing this to my attention.

I do not think I own that domain anymore.

I have deleted the link to the demo site and will add it soon after setting it up elsewhere.

**Comment by srikat** [comment]
@gonebeta Here's the working link for the theme demo:

http://one-pager-genesis.wpdemos.co/
