### ISSUE TITLE
Additional Sidebars

### ISSUE THREAD

**Issue by Launchpad135** [srikat/one-pager-genesis#3]
I need To have more Sidebars to accommodate additional widget areas besides Welcome,  About us, Contact etc........These Sidebars need to be on the Main Homepage so that the parallax scrolling effect works......
What is the bst way to add additional Sidebars? 

Also, how do you add additional background images for the new Sidebar areas?

Appeciate your assistance
Greg

**Comment by srikat** [comment]
Answered here: https://github.com/srikat/one-pager-genesis/issues/4
